import * as durable from "@notation/reconciler/durable";
import {
  createLoggerReconcilerSubscriber,
  type ReconcilerEventEmitter,
  type ResourceRegistry,
} from "@notation/reconciler";
import { getResourceGraph } from "src/orchestrator/graph";
import { runDurableWorkflow, type NodeDurableRuntime } from "../durable-runtime";

export type DeployAppOptions = {
  entryPoint: string;
  driftDetection?: boolean;
  dryRun?: boolean;
  maxOperationAttempts?: number;
  registry?: ResourceRegistry;
  runtime?: NodeDurableRuntime;
  /** Required: the resume handle for this run, generated by the caller. */
  executionId: string;
  databasePath?: string;
  emit?: ReconcilerEventEmitter;
};

export async function deployApp({
  entryPoint,
  // Defaulted in one place: the reconciler's drift gate treats absent as on.
  driftDetection,
  dryRun = false,
  maxOperationAttempts,
  registry,
  runtime,
  executionId,
  databasePath,
  emit = createLoggerReconcilerSubscriber(),
}: DeployAppOptions): Promise<void> {
  const graph = await getResourceGraph(entryPoint);
  await runDurableWorkflow(
    { entryPoint, workflowId: "deploy", runtime, databasePath, executionId },
    (step, executionId, runtime) =>
      durable.deploy(step, {
        executionId,
        resources: graph.resources,
        state: runtime.state,
        registry,
        emit,
        dryRun,
        driftDetection,
        maxOperationAttempts,
      }),
  );
}
