import * as durable from "@notation/reconciler/durable";
import {
  createLoggerReconcilerSubscriber,
  type ReconcilerEventEmitter,
  type ResourceRegistry,
} from "@notation/reconciler";
import { getResourceGraph } from "src/orchestrator/graph";
import { runDurableWorkflow, type NodeDurableRuntime } from "../durable-runtime";

export type DestroyAppOptions = {
  entryPoint: string;
  maxOperationAttempts?: number;
  registry?: ResourceRegistry;
  runtime?: NodeDurableRuntime;
  /** Required: the resume handle for this run, generated by the caller. */
  executionId: string;
  databasePath?: string;
  emit?: ReconcilerEventEmitter;
};

export async function destroyApp({
  entryPoint,
  maxOperationAttempts,
  registry,
  runtime,
  executionId,
  databasePath,
  emit = createLoggerReconcilerSubscriber(),
}: DestroyAppOptions) {
  const graph = await getResourceGraph(entryPoint);
  await runDurableWorkflow(
    { entryPoint, workflowId: "destroy", runtime, databasePath, executionId },
    (step, executionId, runtime) =>
      durable.destroy(step, {
        executionId,
        resources: graph.resources,
        state: runtime.state,
        registry,
        emit,
        maxOperationAttempts,
      }),
  );
}
